version: "3"

services:
  redis:
    image: redis
    # ports:
    #   - 6379:6379

  monitor-api:
    image: svladimirovich/home-made-cluster-monitor-api
    build:
      context: ./monitor-api
      dockerfile: Dockerfile
    environment: 
      - PORT=5000
      - REDIS_HOST=redis
    # ports:
    #   - 5000:5000
  
  monitor:
    image: svladimirovich/home-made-cluster-monitor
    build:
      context: ./monitor
      dockerfile: Dockerfile
    environment:
      - API_HOST=monitor-api:5000
    ports:
      - 8080:80
  
  worker:
    image: svladimirovich/home-made-cluster-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    deploy:
      # restart_policy:
      #   condition: on-failure
      #   delay: 10s
      #   max_attempts: 3
      #   window: 120s        
      replicas: 5
    environment:
      - REDIS_HOST=redis
      - ITERATION_INTERVAL=1
      - RETRY_INTERVAL=3
      - MASTER_EXPIRATION=2
    depends_on:
      - redis
      